version: "2.0"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: changeMe
        volumes:
            - mysql-data:/var/lib/mysql
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
    
    adminer:
        image: adminer:4.8.1
        restart: always
        ports:
            - 8080:8080

    suitecrm:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes: 
            - ./:/var/www/html/
            - /php.ini:/usr/local/etc/php/conf.d/php.ini
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - db

volumes:
    mysql-data: